const ResultCode = {
    CREATED: 'CREATED',
    NOT_FOUND: 'NOT_FOUND',
    NO_CONTENT: 'NO_CONTENT',
    DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    SUCCESS: 'SUCCESS',
    DEFAULT: 'DEFAULT',
    INTERNAL_ERROR: 'INTERNAL_ERROR'
};

module.exports = ResultCode;